### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by bigsecretofind** [ghostsb/ghost#13]
C:\Users\Admin\Desktop\ghost-main>python ghost.py
Traceback (most recent call last):
  File "ghost.py", line 24, in <module>
    from utils import scripts
  File "C:\Users\Admin\Desktop\ghost-main\utils\scripts.py", line 8, in <module>
    def add_script(filename: str, globals_: dict[str, Any], locals_: Mapping[str, Any]) -> None:
TypeError: 'type' object is not subscriptable

i had to downgrade from latest python oct 26 to 3.8.0 because my pip install wouldnt correctly work

**Comment by 9qz** [comment]
use pythons uninstaller (you can find it in the location where you installed python) and install latest version
